object Versions {
    const val ANDROIDX_CORE = "1.10.1"
    const val ANDROIDX_LIFECYCLE = "2.6.1"
    const val ANDROIDX_TEST = "1.1.5"
    const val COIL = "2.4.0"
    const val COMPOSE_ACTIVITY = "1.7.2"
    const val COMPOSE_BOM = "2022.10.00"
    const val COMPOSE_NAVIGATION = "2.6.0"
    const val ESPRESSO = "3.5.1"
    const val JUNIT = "4.13.2"
    const val KOIN = "3.4.2"
    const val KOTLIN = "1.8.22"
    const val OKHTTP = "4.11.0"
    const val RETROFIT = "2.9.0"
}
